export const migrations = [
 "Roles",
 "Users",  
 "Subjects",
 "Levels",
 "Parents",
 "Teachers",
 "Students",
 "Payments",
 "Courses",
 "Subjects_Teachers",
 "Parents_Students",
 "Courses_Students",
 "Courses_Teachers",
];